#!/bin/bash


_get_ziplink_matrix () {
    local matrixzip
    matrixzip='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "qithoniq" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3FpdGhvbmlxL21hdHJpeC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $matrixzip ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/matrix.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3FpdGhvbmlxL21hdHJpeC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}

_get_matrixlink () {
    local matrixzip
    local matrixlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "qithoniq" ]]
    then
        matrixlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3FpdGhvbmlxL21hdHJpeA==" | base64 -d`
    elif [[ $UPSTREAM_REPO =~ $matrixzip ]]
    then
        matrixlink=`echo "${UPSTREAM_REPO}"`
    else
        matrixlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3FpdGhvbmlxL21hdHJpeA==" | base64 -d`
    fi
    echo "$matrixlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_matrixpack_git() {
    $(_run_python_code 'from git import Repo
import sys
MATRIX_REPO = "https://github.com/qithoniq/matrix"
ACTIVE_BRANCH_NAME = "master"
matrixrepo = Repo.init()
origin = matrixrepo.create_remote("temponame", MATRIX_REPO)
origin.fetch()
matrixrepo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
matrixrepo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_matrix_git() {
    local matrixlink=$(_get_matrixlink)
    $(_run_python_code 'from git import Repo
import sys
MATRIX_REPO="'$matrixlink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "master"
matrixrepo = Repo.init()
origin = matrixrepo.create_remote("temponame", MATRIX_REPO)
origin.fetch()
matrixrepo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
matrixrepo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local matrix
    matrix="matrix.zip"
    echo "جاري تنزيل اكواد السورس "
    wget -q $(_get_ziplink_matrix) -O "$matrix"
    echo " تفريغ البيانات "
    MATRIXPATH=$(zipinfo -1 "$matrix" | grep -v "/.");
    unzip -qq "$matrix"
    echo " تم التفريغ "
    echo " يتم التنظيف "
    rm -rf "$matrix"
    sleep 5
    _run_matrixpack_git
    cd $MATRIXPATH
    _run_matrix_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    بدء ماتركس العربي   "
    echo "

    "
    python3 -m matrix
}

_set_bot
